/** Class names for workflow-shell.css (static file in /public, no CSS modules). */
export const wf = {
  page: "wf-page",
  header: "wf-header",
  headerLogo: "wf-header-logo",
  headerMascot: "wf-header-mascot",
  headerTitle: "wf-header-title",
  tabBar: "wf-tab-bar",
  tab: "wf-tab",
  tabActive: "wf-tab-active",
  body: "wf-body",
  embedFrame: "wf-embed-frame",
  widgets: "wf-widgets",
  widgetsRight: "wf-widgets-right",
  widget: "wf-widget",
  widgetChromeless: "wf-widget-chromeless",
  iframeWrap: "wf-iframe-wrap",
  iframePlaceholder: "wf-iframe-placeholder",
  dgActions: "wf-dg-actions",
  dgActionRow: "wf-dg-action-row",
  dgBtn: "wf-dg-btn",
  dgBtnInline: "wf-dg-btn wf-dg-btn-inline",
  dgProgress: "wf-dg-progress",
  dgProgressFill: "wf-dg-progress-fill",
  dgProgressLabel: "wf-dg-progress-label",
  dgStatus: "wf-dg-status",
  genieStack: "wf-genie-stack",
  geniePanes: "wf-genie-panes",
  geniePaneOutput: "wf-genie-pane-output",
  geniePaneInput: "wf-genie-pane-input",
  genieTextarea: "wf-genie-textarea",
  genieOutput: "wf-genie-output",
  genieHeadingRow: "wf-genie-heading-row",
  genieActions: "wf-genie-actions",
  genieSecondary: "wf-genie-secondary",
  modalBackdrop: "wf-modal-backdrop",
  modalPanel: "wf-modal-panel",
  modalActions: "wf-modal-actions",
} as const;
